# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
  - stage: build
    displayName: 'master-branch-build'
#build job
    jobs:
      - job: build
        displayName: 'master-branch-build'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Npm@1
            displayName: 'npm install'

          - task: Npm@1
            displayName: 'npm run build'
            inputs:
              command: custom
              customCommand: 'run build'

          - task: CopyFiles@2
            displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/build'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifact: drop'
  - stage: release
    displayName: 'dev-env-release'
#release job
    jobs:
      - job: release
        displayName: 'dev-env-release'
        pool:
              vmImage: 'ubuntu-latest'
        steps:
         - task: AzureRmWebAppDeployment@4
           inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: <subscriptionNameHere>(<subscriptionIDHere>)'
            appType: 'webAppLinux'
            WebAppName: '<appNameHere>'
            packageForLinux: '$(Build.ArtifactStagingDirectory)'
            RuntimeStack: 'PHP|7.3'
