# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    - master
    
    stages:
      - stage: build
        displayName: 'master-branch-build'
    
        #build jobs
        jobs: 
          - job: build
            pool:
              vmImage: 'ubuntu-latest'
    
            variables:
              buildConfiguration: 'Release'
    
            steps:
            - task: DotNetCoreCLI@2
              inputs:
                command: 'restore'
                projects: '**/*.csproj'
                feedsToUse: 'select'

            - task: DotNetCoreCLI@2
              inputs:
                command: 'build'
                projects: '**/*.csproj'
                arguments: '--configuration $(BuildConfiguration)'
                
            - task: DotNetCoreCLI@2
              inputs:
                command: 'publish'
                publishWebProjects: true
                arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
                
            - task: PublishBuildArtifacts@1
              inputs:
                PathtoPublish: '$(build.artifactstagingdirectory)'
                ArtifactName: 'drop'
                publishLocation: 'Container'
    
     